version: 1
services:
  - type: web
    name: taskmaster-pro
    env: 
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: MONGODB_URI
        value: mongodb+srv://brianmayoga:1uZIQRDuX5Km4flb@cyton.etkwfr8.mongodb.net/?retryWrites=true&w=majority&appName=Cyton
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: briancreatives@gmail.com
      - key: MAIL_PASSWORD
        value: vadt zjjn rfgc zerf
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: briancreatives@gmail.com
      - key: MAIL_FROM_NAME
        value: Task Management System
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    plan: free
